### ISSUE TITLE
[BUG] Reconstruction fails in the middle of processing due to insufficient RAM

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/recOrder#108]
At AQLM, we had a computer with 64GB RAM. This computer could not handle retardance & phase reconstruction  of 2kx2kx50 stack. It is optimal to allocate memory for all variables required for reconstruction before reconstruction starts. This issue may need to be moved to waveOrder if allocation is done by methods there.

**Comment by talonchandler** [comment]
Reading between the lines of #107 and #108, I'm guessing that you requested a big acquisition+reconstruction then received OOM during the reconstruction you lost everything---definitely a major issue.

I think the full solution will involve:
1) Solving #107 so that data is always saved to disk after acquisition. After this is fixed is solved we can request expensive recons without worrying about this type of catastrophe.
2) Like you suggest: preallocating the arrays so that waveorder fails early and gracefully if you ask too much. I expect this will involve moving the preallocation calls to the `waveorder.waveorder_microscopy` constructor within `try`/`except` blocks.

**Comment by talonchandler** [comment]
3. Recreating and testing this bug might be a bit tricky, but [this discussion](https://stackoverflow.com/questions/41105733/limit-ram-usage-to-python-program) has some useful snippets for artificially limiting the amount of RAM available to python.

**Comment by talonchandler** [comment]
I'm flagging this issue for discussion because I think it will take more effort and give less reward than I initially thought. 
We may've already reached a satisfactory solution by saving to disk before reconstruction starts (issue #107 solved by PR #146). 

Here are two solutions we've discussed:

**Solution 1: Preallocate all of the arrays so that a large reconstruction fails early.**

This solution will work, and I have only minor concerns about the effort required to preallocate the correct arrays in `waveorder` since there are many paths through the `waveorder_microscopy` class. 

However, my **major concern is that preallocating the arrays will make our memory performance worse**. By tying up all of our memory early in a reconstruction we will have less free memory to work with. We can partially sidestep this problem by manually freeing up memory when we're finished with it, but this is additional work and only a bandage since we'll be using a *lot* of memory at the start of the recon. 

**Solution 2: Find empirical heuristics for when memory usage will be too large, and warn the user if they make a request that's larger than the RAM available.**

A heuristic like "warn the user when the estimated RAM required to complete the reconstruction without swapping is larger than the available RAM" will take a fair amount of effort (the heuristic probably needs to depend on xy dimension, z dimension, and recon type?) for very little reward (the warning makes the user aware of a potential RAM limitation). 

If I was a user and saw a RAM warning from an application, I would watch my task manager and see what happens...

I'll propose a **Solution 3: warn the user if their computer has <32 GB of RAM and point them to a task manager**. 

The warning message might be:
"recOrder reconstructions often require more than the XX GB of RAM that this computer is equipped with. We recommend starting with reconstructions of small volumes ~1000 x 1000 x 10 and working up to larger volumes while monitoring your RAM usage with Task Manager or `htop`."

Adding @ieivanov
