### ISSUE TITLE
Should we have an `orientation offset` field, and what should it look like?

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#247]
Following some of the orientation offsets observed on mantis, the possibility of an `orientation offset` field has arisen. I can imagine a few different choices:

Option 1: a field that accepts a float/int in degrees and shifts the visualization or reconstruction. This might be nice, but @edyoshikun raised a few concerns about accidental abuse of this feature. Would this feature be used to "cover up" misaligned microscopes?
Option 2: a checkbox that rotates the visualization or reconstruction by 90 degrees. I think this solution would solve many coarse problems without giving the user "too much" flexibility. 
Option 3: no offset.

@edyoshikun, @ieivanov, @mattersoflight what do you think. How much should we constrain the user to align their system "correctly"? I'm leaning towards option 2.

**Comment by mattersoflight** [comment]
Yes. I suggest adding that to reconstruction parameters panel.

**Comment by edyoshikun** [comment]
I do think that the `orientation offset` setting should be an option considering that the way the LC's are mounted at the moment in the meadowlark LC sandwich is rotated 90deg from the previous versions. Since LCB in the mantis setup is rotated 90deg then I can't think of another way to fix this except with the `orientation offset`. 

I do think that this option should be somewhat of a `super user` setting considering the amount of debugging we had to do to reach this conclusion. As @mattersoflight suggested, once we have proper documentation we can include in a troubleshooting section examples of what problems look like and the fixes and when to use this setting.

**Comment by talonchandler** [comment]
Apologies for my accidental early send...edited above. I'm slightly concerned about providing too much flexibility and covering up over deeper issues, but my concern is fairly minor.

**Comment by edyoshikun** [comment]
Option 2 seems like the right thing to do to limit the user and to provide solution to the only possible LC orientation alignment trusting that meadowlark alignment at 0 or 90 deg.

Just for the record.. the original mantis LC was showing ~15 deg offset and the two new LCs show 90deg offset.

**Comment by mattersoflight** [comment]
I agree that fixing the offset to 0 and 90 degrees will avoid masking the alignment issues during acquisition. 
We learned from Meadowlark that tolerance in the alignment of LCs is ~5 degrees. So, we should apply a smaller orientation offset. But, this correction will typically be done in a reconstruction script.
