### ISSUE TITLE
`examples/3D-pol-to-birefringence.py` should write phase and birefringence results to a single zarr

### ISSUE THREAD

**Issue by talonchandler** [mehta-lab/recOrder#296]
Instead of writing to two different zarrs, this example script should write to a single zarr.

**Comment by ieivanov** [comment]
I think it's useful to be able to write several different zarr stores for a single position/dataset. For example, I may want to write Stokes parameters, birefringence recon, and phase recon to separate zarr stores. Is that supported by the OME-ZARR format? Is our zarr writer capable of doing that?

**Comment by ziw-liu** [comment]
> the spec for a single OME-ZARR dataset does not allow subsets of channels to be saved to different .zarr stores

I'm not sure that I understood the question. The spec for a single OME-Zarr store allows for arbitrary numbers of channels. If separate Zarr stores are needed, we just make sure that each one of them is compliant with the spec and manually keep track of the separate stores.

You are right that the readers won't be able to 'intelligently' load multiple Zarr stores, since there's no information (metadata) that tells a reader that these separate datasets are related in a defined way.

**Comment by talonchandler** [comment]
@ieivanov can you help us understand the use case for having subsets of channels saved to different zarrs? Can good channel names within a single zarr solve this, or are you thinking about "irregular" datasets where you e.g. take 2D fluorescence and 3D brightfield?

**Comment by ieivanov** [comment]
Transferring a comment to this discussion.

I am imagining a file structure like this.

```
dataset
   FOV1
      data1.zarr
      data2.zarr
   FOV2
      data1.zarr
      data2.zarr
```

Here data1 and data2 come from the same FOV, but may have different channels (e.g. biref vs Stokes images) or different dimensions (e.g. Z stacks vs Z projections or full resolution vs 3x3 median filter images). This is perfectly possible using the zarr standard, but may not be allowed by the ome-zarr standard - I can see how this will be difficult for a viewer to handle. Does ome-zarr require single .zarr store per position?

**Comment by ziw-liu** [comment]
> Here data1 and data2 come from the same FOV, but may have different channels (e.g. biref vs Stokes images)

For non-HCS stores, having different channels should work just fine.

> This is perfectly possible using the zarr standard, but may not be allowed by the ome-zarr standard - I can see how this will be difficult for a viewer to handle.

Your estimation is accurate. The Zarr-python implementation and the OME-Zarr specification allow having arrays of different dimensions in a single store/FOV, and the `multiscales` pyramid representation actually *requires* support for such behavior. The difficulty of having different dimensions (esp. projected dimensions) in the same store is only due to how the `ome-zarr-py` reader implements data loading, which tries to stitch all the Z-arrays in to a single Dask array, and the broadcasting of `multiscales` is defined by the `coordinateTransformation` metadata. My (naÏve) suggestion would be to keep each FOV in a single store to avoid data fragmentation and to write a simple napari script (or extend the `recOrder` napari reader) if we anticipate having data emerging in that format.

> Does ome-zarr require single .zarr store per position?

It does not. The specification only regulates the data and metadata within a Zarr store.

**Comment by ziw-liu** [comment]
For datasets where the only source of dimensional mismatch comes from projections, an easy way out is to allow for some data duplication and repeat the projected plane over the projected axis (which isn't physically 'wrong' IMO).
