### ISSUE TITLE
Extinction coefficient increasing with reducing swing

### ISSUE THREAD

**Issue by Soorya19Pradeep** [mehta-lab/recOrder#305]
Increasing extinction coefficient on calibration with smaller swing values

The extinction value increase on each calibration run on Hummingbird as the swing value is decreased. All other parameters were kept constant The snapshots below were captured at swing values of 0.1, 0.03 and 0.01 by @mattersoflight . 

<img src="https://user-images.githubusercontent.com/101817974/212156530-25aa1380-fd54-4029-a300-3b6fcbbcbe56.png" width=40% height=40%>

<img src="https://user-images.githubusercontent.com/101817974/212156561-d4e8baf8-eb9a-4703-8949-72e4e025bfb0.png" width=40% height=40%>

<img src="https://user-images.githubusercontent.com/101817974/212156682-462560e4-239c-434f-9f8a-804761f200c2.png" width=40% height=40%>

Operating system: Windows
Python version:
Conda environment: recOrder
MicroManager/pycromanager version:

**Comment by ziw-liu** [comment]
It looks like the Swing is indeed involved when we calculate the extinction ratio:
https://github.com/mehta-lab/recOrder/blob/7e10ae59a1ed28cf28052b97404a2c0eba4369ff/recOrder/calib/Calibration.py#L819-L827

@Soorya19Pradeep Thanks for reporting. Can you also include a title for this issue?

**Comment by Soorya19Pradeep** [comment]
@ziw-liu , thank you for pointing it out. I have added a heading for the issue

**Comment by ziw-liu** [comment]
> It looks like the Swing is indeed involved when we calculate the extinction ratio

And the relation between Swing and Extinction is pretty steep in this calculation:
<img width="240" alt="Screen Shot 2023-01-12 at 11 20 38" src="https://user-images.githubusercontent.com/67518483/212161534-62631691-882c-4051-b46f-a38e3ea7b0a6.png">

**Comment by Soorya19Pradeep** [comment]
@ziw-liu , as you pointed out the extinction coefficient increases disproportionally with increase in swing. The extinction coefficient is above 1000 for a swing of 0.01. @mattersoflight  did point to the fact that the interpolation maybe faulty, possibly due to a mathematical error in equations used.

**Comment by talonchandler** [comment]
Thanks for reporting and documenting this @Soorya19Pradeep, and thanks for bringing up the relevant lines @ziw-liu. 

My mental model of the extinction metric is that the `(intensity_elliptical - black_level) / (intensity_extinction - black_level)` term is a "modulation depth" term and the `(1 / np.sin(np.pi * swing) ** 2)` term is a "normalize to your expectations" term. As swing decreases, we expect the modulation depth to go down like `np.sin(np.pi * swing)**2`, while the normalization term balances this expectation so that the resulting extinction is independent of swing and is a good indicator of how "good" your calibration is. 

One way this metric might fail in the way you're observing is if there is significant "background leakage"---counts when the shutter is open but the light source is off. Leakage will reduce the modulation depth and could overwhelm any real modulation for small swings. @Soorya19Pradeep did you have the box open when you made these measurements? Next time you're at the scope can you see if reducing leakage reduces this effect? 

If leakage explains this effect, we might consider making leakage measurements when we're calculating extinction. If leakage doesn't explain this effect, I'll have to think more. Either way, I don't think swing-dependent extinction metrics should be a blocker.

**Comment by Soorya19Pradeep** [comment]
Thank you for the response @talonchandler . To explain the conditions in which we performed the measurements, the calibration was performed in an empty well of a 12 well plate with just media. The box was closed and we could see the light as we were imaging at 20X in the middle of the well. The intensity of the light was also adjusted to best utilize the dynamic range on the camera at all states of LC, but not too high that it causes saturation.

We also repeated the measurements without a sample, taking the plate off from the light path as we suspected the glass might be under stress as it is stuck on the 12-well frame. Do you think it is a good idea to replicate the measurement on a Kazansky target?

**Comment by mattersoflight** [comment]
Thanks @Soorya19Pradeep for logging the bug, @ziw-liu for pointing out the lines. 

There is a simple mistake in the scaling factor - possibly caused by a misreading of units of swing. In our code, we express swing in terms of the fraction of wavelength. Optically speaking, a swing of 0.5 implies the introduction $\pi$ retardance by the LC of the universal polarizer, which leads to a polarization state parallel to the analyzer state. A swing of 1 implies retardance of $2\pi$, which leads to a polarization state perpendicular to the analyzer state, i.e., same as the extinction state.

I think the correct equation is: 
```math
E_{extinction} = \frac 1 {\sin (2 \pi S_{swing} )} \cdot \frac {I_{elliptical} - I_{black}} {I_{extinction} - I_{black}}
```

The following picture hopefully clarifies the derivation by visualization:
![image](https://user-images.githubusercontent.com/2934183/212213470-d71579a4-0c15-4184-a256-c4b7a8d8c48a.png)

**Comment by ziw-liu** [comment]
Does this bug affects our existing heuristics about what is a 'good' extinction (e.g. $E_{extinction} \geq 100$)?

**Comment by mattersoflight** [comment]
Our heuristic (extinction more than 200 is good) is based on sound
arguments about dynamic range of measurements, and is correct. We need to
fix this bug and check if the code computes close to true extinction. This
can be done by setting swing to 0.5 and generating polarization state that
is parallel to analyzer.

**Comment by ziw-liu** [comment]
> This can be done by setting swing to 0.5 and generating polarization state that is parallel to analyzer.

Along this line, maybe we can change the 'calculation' of extinction to 'measuring' by automatically performing this procedure in `recOrder`.

**Comment by ziw-liu** [comment]
When testing https://github.com/mehta-lab/recOrder/pull/306/commits/2ef632a55b069ad6763b29047491d7133f3960d0 with @Soorya19Pradeep, we found that the updated equation would result in ~10 extinction for swings 0.1, 0.03, and 0.01 on the Hummingbird, which is not consistent with the microscope's performance. 

We also tried to calibrate with swing of 0.1 (extinction intensity 252, black level 101) and add 0.5 to the retardance value in MM to try to measure the maximum intensity of 14351. This works out to an extinction ratio of 94.37. However these values would give:

```math
I_{elliptical} = I_{black} + ( I_{max}- I_{extinction} ) \cdot \sin (2 \pi S_{swing}) = 8388
```

while recorder logs elliptical states intensity values (`I0`, `I45`, `I90`, `I135`) at around 1102.

@mattersoflight Can you explain again how the maximum intensity should be measured?

<details>
  <summary>Click to expand console logs</summary>
  
  ```log
17:40:14 INFO Starting Calibration
17:40:14 INFO Calculating Black Level ...
17:40:22 INFO Black Level: 101

17:40:22 INFO Calibrating State0 (Extinction)...
17:40:59 INFO LCA State0 (Extinction) = 0.290
17:40:59 INFO LCB State0 (Extinction) = 0.520
17:40:59 INFO Intensity (Extinction) = 252
17:40:59 INFO --------done--------
17:40:59 INFO Calibrating State1 (I0)...
17:41:00 INFO LCA State1 (I0) = 0.190
17:41:00 INFO LCB State1 (I0) = 0.520
17:41:00 INFO Intensity (I0) = 1102
17:41:00 INFO --------done--------
17:41:00 INFO Calibrating State2 (I45)...
17:41:06 INFO LCA State2 (I45) = 0.290
17:41:06 INFO LCB State2 (I45) = 0.428
17:41:06 INFO Intensity (I45) = 1103
17:41:06 INFO --------done--------
17:41:06 INFO Calibrating State3 (I90)...
17:41:13 INFO LCA State3 (I90) = 0.398
17:41:13 INFO LCB State3 (I90) = 0.520
17:41:13 INFO Intensity (I90) = 1102
17:41:13 INFO --------done--------
17:41:13 INFO Calibrating State4 (I135)...
17:41:19 INFO LCA State4 (I135) = 0.290
17:41:19 INFO LCB State4 (I135) = 0.607
17:41:19 INFO Intensity (I135) = 1102
17:41:19 INFO --------done--------
17:41:19 INFO
=======Finished Calibration=======

17:41:19 INFO EXTINCTION = 11.27
  ```
</details>

**Comment by ziw-liu** [comment]
> However these values would give $I_{elliptical} = I_{black} + ( I_{max}- I_{extinction} ) \cdot \sin (2 \pi S_{swing}) = 8388$

Looking at the plot [above](https://github.com/mehta-lab/recOrder/issues/305#issuecomment-1381177113), the sinusoid term in $I_{elliptical} = I_{black} + ( I_{max}- I_{extinction} ) \cdot \sin (2 \pi S_{swing})$ should have a phase shift of $- \frac {\pi} {2}$ (quarter wave) so that the lowest intensity shows up at swing of 0. And the center amplitude should be $I_{max}$ instead of $I_{black}$ so that the lowest value is $(I_{max} - I_{ext}) \cdot (-1) + I_{max} = I_{ext}$. So something like:

```math
I_{elliptical} = I_{max} - ( I_{max}- I_{extinction} ) \cdot \cos (2 \pi S_{swing})
```

Then the calculated extinction ratio would be:

```math
E_{(S)} = \frac {1} {1 - \cos{(2 \pi S)}} \cdot \frac {I_{elliptical} - I_{extinction}} {I_{extinction} - I_{black}} + 1
```

But this doesn't seem quite right either...

**Comment by ziw-liu** [comment]
> Then the calculated extinction ratio would be:
$E_{(S)} = \frac {1} {1 - \cos{(2 \pi S)}} \cdot \frac {I_{elliptical} - I_{extinction}} {I_{extinction} - I_{black}} + 1$
But this doesn't seem quite right either...

Compared to the correct expression $\text{Extinction ratio (new)} = \frac{1}{\sin^2(\pi S)}\frac{I_{\text{ellip}} - I_{\text{ext}}}{I_{\text{ext}} - I_{\text{bl}}} + 1.$ in #308:

$$
E_{(S) (wrong)}
\= \frac {1} {1 - \cos{(2 \pi S)}} \cdot \frac {I_{elliptical} - I_{extinction}} {I_{extinction} - I_{black}} + 1
\= \frac {1} {2\sin^2{(\pi S)}} \cdot \frac {I_{elliptical} - I_{extinction}} {I_{extinction} - I_{black}} + 1
$$

A factor of 2 was mixed in at some point.
