### ISSUE TITLE
Acquire Birefringence file IO error

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#32]
`Acquire Birefringence` button throws this warning:

```
unclosed file <_io.FileIO name='D:\\2022_01_10 recorder testing\\recOrderPluginSnap_1\\recOrderPluginSnap_1_MMStack_Default.ome.tif' mode='rb' closefd=True>
```

and the MM display window closes at the end of an acquisition.

**Comment by camFoltz** [comment]
So the first issue is actually a WaveorderReader issue but should be fixed in [this waveOrder PR](https://github.com/mehta-lab/waveorder/pull/60)

The second issue is not actually a bug but a design choice.  I figured most users would not care about seeing the raw data snaps and would just like to see the birefringence output.  For those with more of a trained eye I do see how seeing the raw data could be useful, I just didn't want the screen to inevitably be clogged by all of these raw data windows on successive snaps.

What do you think here?  Would you prefer to have the raw data left open?  From a data reading / programming standpoint either option works fine-- this is just a usability decision

**Comment by ieivanov** [comment]
Yeah, I see your point. MM leave acquisition windows open, so I expected this one to stay open as well. I'd say if we decide to close the raw data acquisition window, then we should add the raw data channels as invisible layers in napari, so we can still look at it together with the reconstruction

**Comment by camFoltz** [comment]
closing this issue as it has been fixed in the waveOrder PR and we have a separate issue for when to close the raw MM data during a snap acquisition
