### ISSUE TITLE
write zarr stores acquired during calibration with ome-zarr compatible writer, such that they load well in napari

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/recOrder#43]

**Comment by camFoltz** [comment]
So this is fixed for when the user acquires birefringence / phase snaps, but not for the data listening module zarr store.  The difference here is that the user is only acquiring a single FOV in the snap mode, while the data listening can have multiple positions.  

In order to have a lazy loading of a multi-position acquisition in a single napari layer, all of that data (P, T, C, Z, Y, X) needs to exist in a single zarr array.  `However doing this breaks OME-zarr standards, so we do not use the WaveorderWriter in this case.`

I don't immediately see a way around this, as implementing the data listening as OME-zarr would require every position to be a new napari layer, crowding the layers and becoming confusing to track.

**Comment by camFoltz** [comment]
closing this as it is mainly fixed in #31 . Will start a new issues for a subsequent release.
