### ISSUE TITLE
Better tracking of calibration and reconstruction metadata

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#47]
In the calibration plugin it would be useful to include a field for user notes. 

I often run multiple rounds of calibration, sometimes under different settings. Right now, I need to save those under different folders or change the filename of `calibration_metadata.txt` to sometime more meaningful. A Notes field would allow me to jot down something quick about the microscope setup that may not be captured in the metadata. In this case, metadata files should not be overwritten, but instead carry a numeric extension, e.g. `calibration_metadata_9.txt`.

Maybe the same Notes field would be useful in the Acquisition widget too

**Comment by camFoltz** [comment]
I can put a notes section under the advanced tab,  I am hesitant to start crowding the main UI with a lot of features that will only be used by a small percentage of users.  That will allow you to write a note directly into the last-calibrated metadata file.

The only thing I am worried about with incrementing the filenames of the metadata file is that if a user is testing the system and performing many calibrations (most of which don't need to be saved) then the folder can quickly become crowded.  My idea here would be to also add a checkbox in the advanced tab that allows the user to choose whether or not to overwrite calibration metadata files (default will be `overwrite=True`).  What do you think of this @ieivanov ?

I am also worried about the numeric extension not being distinguishable enough for a user to remember which calibration it corresponded to.  We may just have to let that be the fault of the user, but my only other idea is to add a timestamp to the metadata file to help with this.

**Comment by mattersoflight** [comment]
I also agree with @ieivanov  that one needs to track metadata for different calibrations (e.g., I am trying swings of 0.03, 0.05, 0.1). @camFoltz I think calibration_<timestamp> is a good format. There is not need to overwrite metadata files since they are tiny. The timestamp gives you a sense of when you ran calibration e.g. at the start of your session, middle or end.

Notes field is also nice to have. It can be a text field next to "Plot" and "Advanced", it can become a "Notes" field, which gets saved in the JSON whenever metadata is written.
![image](https://user-images.githubusercontent.com/2934183/150592456-d622f3e9-ee41-42b3-bd48-5d89e67e456f.png)

Building on this idea, right now we are saving calibrated parameters for pixel-wise reconstruction of retardance. We should document the phase reconstruction parameters in the same way, so that off-line processing can take that as input (#42). How does the current implementation pull the parameters required for phase reconstruction?

**Comment by camFoltz** [comment]
@mattersoflight So phase is a bit tricky because we can't really pull that information from Micromanager.  The only parameter we can pull is the z-step size.  Otherwise the user will have to manually input those fields into the UI here or in the config file when they do processing.  
![Screen Shot 2022-01-21 at 2 22 23 PM](https://user-images.githubusercontent.com/56048121/150607998-d7f66685-5599-492e-83af-f9c2ae9d8821.png)

Currently if the user were to take a phase snap then the parameters are saved under the zarr attributes (if they chose to save the snap to disk) so they can refer back to the reconstruction settings.

**Comment by ieivanov** [comment]
I like the idea of a new lab next to Advanced.

We should think about when the notes can be added - before calibration (most likely), after calibration (often useful if we forget to make a note ahead of time), and if we should clear the Notes field after each calibration run.

I'd suggest requiring the user to add notes before the calibration is finished. But we should also make it easy to open the `calibration_metadata.txt` files and add notes there after the fact. In that case, it would be best to put the Notes data at the very end of the file.

**Comment by camFoltz** [comment]
fixed in #31 .  Added a notes tab with a notes field that will automatically push the current text in the field to the next calibration file.  Also added a feature to allow the user to push and append notes to the last calibration file.

**Comment by mattersoflight** [comment]
Awesome to have the notes section!
>@mattersoflight So phase is a bit tricky because we can't really pull that information from Micromanager. The only parameter we can pull is the z-step size. Otherwise the user will have to manually input those fields into the UI here or in the config file when they do processing.

I meant to suggest that we log manually entered parameters for phase imaging when the user acquires phase data. I think it is best to put them in a human readable JSON, where they can be edited if need be.

**Comment by camFoltz** [comment]
@mattersoflight Are you suggesting an additional file alongside the zarr file?  The zarr file already contains this information in json format under `.attrs`

**Comment by mattersoflight** [comment]
@camFoltz I am suggesting that we save all calibration parameters (birefringence, phase, fluorescence) in `calibration_metadata.txt` in the top directory, assuming that reconstruction pipeline reads the parameters form this file.

**Comment by camFoltz** [comment]
Thank you for clarifying -- I like this idea.  recOrder does use this metadata file, so I can have the pipeline initially look to see if the user ever entered these parameters in the plugin/metadata file and if not enforce that the user enter them in the config.

**Comment by camFoltz** [comment]
Done -- Microscope parameters will be updated in the last used calibration metadata file if the user proceeds with an acquisition.  Still need to add features to the pipeline to recognize this information

**Comment by mattersoflight** [comment]
I suggest microscope parameters are updated even when a stack is acquired. Also, it is useful to track backgrounds captured at different times during the experiment. Timestamped background stacks are helpful when reconstructing the data later.

**Comment by camFoltz** [comment]
populate metadata whenever an image is snapped (even in background snaps)

**Comment by camFoltz** [comment]
Closing this issue as everything discussed has now been implemented in #31
