### ISSUE TITLE
Calibration plugin looks strange on Windows (e.g. mantis)

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#54]
The calibration plugin looks disproportionate on Windows - sorry, I don't have a screenshot. For example, the Extinction Ratio font is too big for the size of its box. I remember there was a problem with the field below it also. The orientation colormap also seemed quite big. I'll post pictures next time I'm at the microscope

**Comment by camFoltz** [comment]
Yeah I have been working on this a bit today -- unfortunately there have been notable napari issues where it can't render the UI well between different operating systems.  I am trying to optimize it to look well for windows since I imagine that will be the main use case.

Whenever you have screenshots that would be great.

**Comment by mattersoflight** [comment]
snapshot from hummingbird 
![image](https://user-images.githubusercontent.com/2934183/151443350-0bf7fd72-edd7-4f9e-8620-9045df2054de.png)

**Comment by camFoltz** [comment]
@ieivanov I think I've fixed this in the latest changes, let me know if there are still weird issues

**Comment by camFoltz** [comment]
current screenshot from windows

![Screen Shot 2022-01-27 at 4 10 58 PM](https://user-images.githubusercontent.com/56048121/151464212-53a315ca-9f60-476c-8338-821e0f4aba46.png)
