### ISSUE TITLE
Package requirements

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/recOrder#69]
Package requirements are specified both in `setup.cfg` and `requirements\default.txt`. The `opencv-python>=4.5.3.56` causes issues on PowerPC environments.

**Comment by camFoltz** [comment]
@ieivanov On PowerPC you will have to install with the `--no-deps` flag and manually install that packages via conda.  There is not a good way around this.

**Comment by ieivanov** [comment]
That works, thanks!

Should we also put package requirements in only the `setup.cfg` file or under `requirements\default.txt`? Is there a reason they need to be in both places?

**Comment by camFoltz** [comment]
Good call @ieivanov, we can get rid of the requirements files and only specify them in the setup.cfg

**Comment by camFoltz** [comment]
Turns out this requirements folder is needed for github actions to run the the tests

**Comment by talonchandler** [comment]
This issue is mostly addressed by PR #87. 

Cameron is right that github actions set up the environment through the requirements folder, but PR #87 moves the test requirements into the .github/worflows/pytests.yml file. The new workflow uses setup.cfg for the environment, so I've deleted the requirements files/folders. 

After this merge we can use the .cfg only.

**Comment by talonchandler** [comment]
@ieivanov during our installation at the NIC yesterday we didn't need the `--no-deps` flag. Any idea what was different? 

I think #87 addresses your second comment on the .cfg and requirements.txt files, but I'm not sure if I understand the original issue.
