### ISSUE TITLE
requirements.txt and test the deployment with testpypi

### ISSUE THREAD

**Issue by mattersoflight** [mehta-lab/recOrder#90]
In the PR #87, we removed the requirements.txt since it was not needed for `pip install`. While deploying the package to testpypi, @talonchandler and I realized that testing the deployed package requires that we setup a conda environment with relevant requirements. 

Also, per the [python packaging guide ](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/), the `install_requires` and `requirements.txt` serve two different purposes of installing the minimal dependencies needed to run the software vs installing the concrete dependencies needed to reproduce the dev/test environment.

We should use requirements.txt for this purpose and continue to test the deployment with testpypi.

**Comment by talonchandler** [comment]
I don't think I completely understand the need to reinstate `requirements.txt`. Thanks for your patience. 

It seems like adding the `requirements.txt` is doubly specifying and over specifying our package dependencies. I think we want to shoot for a single source of truth for package dependencies (so that we don't need to manage them both), and abstract constraints instead of concrete constraints (to let `pip` sort out the dependencies). 

I think the issue we ran into yesterday was a TestPyPI issue, not a `requirement.txt` issue. IIRC we ran:
`pip install --index-url https://test.pypi.org/simple/ recOrder-napari`
but this failed because it couldn't find the dependencies on TestPyPI (since they live on PyPI). 

If we instead run:
`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ recOrder-napari`
then `pip` knows to look on PyPI as well, and the installation (mostly) succeeds. 

I say mostly because the API and CLI work, but the GUI breaks. Running `napari -w recOrder-napari` gives the manifest warning AND `Plugin 'recOrder-napari' does not provide any dock widgets` then doesn't open napari. I'm looking into it now. 

I'll continue to update progress here.

**Comment by talonchandler** [comment]
I've traced to the issue to the builds. If I use `pip install -e .` from github source or the source downloaded from TestPyPI, everything works as expected. If I use `pip install ...` from either TestPyPI or a locally generated `.whl` file, then the installation works for API and CLI, but not for GUI. 

I expect I'll be able to fix the issue with build settings. Looking closer now...

**Comment by mattersoflight** [comment]
Yes, it does make sense to not have to track the dependencies in two files and to keep them abstract. Good to know one can supply `--extra-index-url`.

**Comment by mattersoflight** [comment]
Having said above, it is good to track the nice-to-have dependencies for the dev environment, such as `grip` or `wget`. To prevent duplication, all needed dependencies can be in `setup.cfg` and the nice-to-haves in `requirements/devlopment.txt` or similar.

**Comment by talonchandler** [comment]
I just figured out the build issue: in `setup.cfg` the line `include_package_data = True` needs to be an `[option]` not `[metadata]`. As an option, this lines tells the build system to include non-`.py` files (like the `.yaml` manifest files), so when this line was in the wrong place the build was broken, but only for the GUI. This fix is currently in the `build-fixes` branch. 

I have uploaded this build to TestPyPI as `0.1.0-beta.2`, and I have tested locally. I will now test on a Windows machine and ask others to test from TestPyPI before I make a pull request. 

Regarding tracking development dependencies: I agree! I think we should have one source of dependencies for normal usage and one source of dependencies for tests and development environments. Right now we have a bit of a kludge in `./.github/workflows/pytests.yml` where we "manually" add each test package. I'll figure out a better way to handle this so that we have one source of dependencies (ideally all in `setup.cfg`, but if I need another file then that will work too).

**Comment by talonchandler** [comment]
I just tested on Windows from Soorya's rig, and the installation of `0.1.0-beta.2` from TestPyPI worked without any manifest errors. I tested API, CLI, and GUI (including connecting to MM) successfully. I'll make a pull request this afternoon.
